### PR TITLE
#47 Add Template Option to Config

### PR DESCRIPTION
**Pull request by DanieliMi**

### CODE REVIEW

**Comment by niklasravnsborg** [comment]
Hey @DanieliMi! I don't want this package to be a wrapper for all the functionality that mpdf has to offer. I just want to support the html to pdf part. So I'm sorry I can not merge this :/

**Comment by amenk** [comment]
I would be happy if this could be merged :-) Should we really make a fork for this? Or would there be a way to make this package extensible? What do you think?

**Comment by amenk** [comment]
I think we just need a way to access the `$this->mpdf` - would this be possible? Or a event callback?

**Comment by niklasravnsborg** [comment]
I hear you @amenk. Unfortunately I see a lot of problems with mpdf. General architecture, quirks and bugs. I think that this package has the potential to be much more extensible and generally useful if it abstracts away all the bonus functionality that mpdf offers.

This way we are not limited by mpdf and can upgrade to another php pdf generator later... Thats my reasoning. What do you think?

**Comment by amenk** [comment]
I understand you. But can we find a way to leverage all features if needed? For example through a callback to fine-configure whatever pdf component is in place?

**Comment by niklasravnsborg** [comment]
Yep that would be an idea. If you want you can submit a PR for a callback based module modification. I don't have the time right now but I will merge it :)

Grüße nach Mainz übrigens 😌

**Pull request closed without merging**
