### PR TITLE
Added all MPdf options to config

### PR DESCRIPTION
**Pull request by JustCarty**
Added all MPdf config options to the constructor.

EDIT:
Apologies for the confusing looking comparison.
I am new to GitHub and I copied and pasted the code to my IDE and then pasted it back in which has caused the horrible file comparison.
I only edited the `$mpd_config` array in the constructor.

### CODE REVIEW

**Comment by niklasravnsborg** [comment]
What happened is that you edited the whitespace. This project uses tabs instead of spaces. Maybe you can change that so I can see what you did.

**Comment by dheroefic** [comment]
@niklasravnsborg can you approve this changes? we really need orientation in config as this wrapper ignored orientation options.

**Comment by niklasravnsborg** [comment]
@dheroefic Sorry for the unresponsiveness. In the mPDF docs it says: 

screenshot 2019-02-11 at 21 34 40

(https://mpdf.github.io/reference/mpdf-functions/construct.html#variables-with-defaults-from-constructor)

Thats why I didn't include it in the default configuration. With this I currently don't see an advantage for including this...

**Comment by JustCarty** [comment]
@niklasravnsborg It's useful for when you have something like:

    $pdf = PDF::loadView('path.to.view', compact('myVariable'), [], [
        'format' => [150, 250],
        'orientation' => 'L'
    ]);

In the above example, I have provided a custom size for the PDF that isn't necessarily something like A4 where I could write `A4-L`.

The logic I was thinking is that if we have the option to specify orientation then it adds flexibility.

**Comment by dheroefic** [comment]
As @JustCarty mentioned above, In case we are using custom paper like in my case Brother Label 24mm and need landscape orientation this wrapper ignored and assumed that orientation always set to potrait. Would great if you can approve the changes as it will add more flexibility to set custom paper and orientation mode.

**Comment by niklasravnsborg** [comment]
@dheroefic Right! Didn't see the use case with custom sizes. Just merged :)

**Pull request merged**
