### PR TITLE
Update to mpdf 8

### LINKED ISSUE #133: Upgrade to mpdf 8
Mpdf 8 was released in March, could we consider upgrade ?

### PR DESCRIPTION
**Pull request by stefanullrich**
This pull request updates to the latest mpdf 8 library (major update).
Which is also needed to support PHP 7.4.

Needed to replace old dummy image provider for tests (service no more online), therefore updated snapshot pdf, too.
Tests are running fine now.

Fixes #133

### CODE REVIEW

**Comment by Jaspur** [comment]
@niklasravnsborg 👍🏼

**Comment by robbieaverill** [comment]
+1 on this

**Comment by gorkau** [comment]
+1 on this. Tested with mdf8 and works fine.

**Comment by cannahan** [comment]
+1

**Comment by niklasravnsborg** [comment]
Merged! Thanks @stefanullrich and thanks guys for your patience :)

**Comment by cannahan** [comment]
@niklasravnsborg new release?

**Comment by o5shorioush** [comment]
Can you add a new release for the change? It's much needed!

**Comment by niklasravnsborg** [comment]
@cannahan @o5shorioush Sure! Just release 4.0 https://github.com/niklasravnsborg/laravel-pdf/releases/tag/v4.0.0

**Comment by cannahan** [comment]
Great, thank you!

**Pull request closed without merging**
